# Generated by Django 4.2.7 on 2023-11-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_eventfeedbaackqr_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfeedbaackqr',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
